apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels: {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
      nodePort: 33000
  selector: {{- include "postgres.selectorLabels" . | nindent 4 }}
